name: Demo GitHub Actions
on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node 17.x
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'

    - name: Install dependencies
      run: npm ci
  test_job_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: npm install && npm test -- --coverage  


